2025-8-26

diff --git a/scripts/colors_and_helpers b/scripts/colors_and_helpers
--- a/scripts/colors_and_helpers
+++ b/scripts/colors_and_helpers
@@ -2,25 +2,28 @@
 #                                    COLORS                                    #
 # ---------------------------------------------------------------------------- #
 
-black_color="\e[38;2;28;28;28m"
-red_color="\e[38;2;175;95;95m"
-green_color="\e[38;2;95;135;95m"
-yellow_color="\e[38;2;135;135;95m"
-blue_color="\e[38;2;95;135;175m"
-magenta_color="\e[38;2;95;95;135m"
-cyan_color="\e[38;2;95;135;135m"
-white_color="\e[38;2;108;108;108m"
+# Reset color
+RESET='\e[0m'
 
-bright_black_color="\e[38;2;68;68;68m"
-bright_red_color="\e[38;2;215;135;135m"
-bright_green_color="\e[38;2;135;175;135m"
-bright_yellow_color="\e[38;2;255;255;175m"
-bright_blue_color="\e[38;2;135;175;215m"
-bright_magenta_color="\e[38;2;135;135;175m"
-bright_cyan_color="\e[38;2;95;175;175m"
-bright_white_color="\e[38;2;255;255;255m"
+# Standard colors
+BLACK='\e[38;2;28;28;28m'
+RED='\e[38;2;175;95;95m'
+GREEN='\e[38;2;95;135;95m'
+YELLOW='\e[38;2;135;135;95m'
+BLUE='\e[38;2;95;135;175m'
+MAGENTA='\e[38;2;95;95;135m'
+CYAN='\e[38;2;95;135;135m'
+WHITE='\e[38;2;108;108;108m'
 
-end_color="\e[0m"
+# Bright colors
+BRIGHT_BLACK='\e[38;2;68;68;68m'
+BRIGHT_RED='\e[38;2;215;135;135m'
+BRIGHT_GREEN='\e[38;2;135;175;135m'
+BRIGHT_YELLOW='\e[38;2;255;255;175m'
+BRIGHT_BLUE='\e[38;2;135;175;215m'
+BRIGHT_MAGENTA='\e[38;2;135;135;175m'
+BRIGHT_CYAN='\e[38;2;95;175;175m'
+BRIGHT_WHITE='\e[38;2;255;255;255m'
 
 # ---------------------------------- HELPERS --------------------------------- #
 
@@ -29,9 +32,9 @@ function command_exists() {
 }
 
 info() {
-	echo -e "${green_color}[+]${end_color} $*"
+	echo -e "${GREEN}[+]${RESET} $*"
 }
 
 error() {
-	echo -e "${red_color}[-]${end_color} Error: $*" >&2
+	echo -e "${RED}[-]${RESET} Error: $*" >&2
 }
