2025-08-22

diff --git a/scripts/gray_curl b/scripts/gray_curl
--- a/scripts/gray_curl
+++ b/scripts/gray_curl
@@ -6,8 +6,8 @@
 #   \/_____/ \/_/ /_/ \/_/\/_/ \/_____/     \/_____/ \/_____/ \/_/ /_/ \/_____/
 
 
-source "$HOME/.local/bin/colors_and_helpers"
-set -euo pipefail
+source "$HOME/.local/bin/colors_and_helpers" || { error "colors and helpers file not found"; exit 1; }
+set -uo pipefail
 IFS=$'\n\t'
 
 # ------------------------------- USAGE BANNER ------------------------------- #
@@ -61,7 +61,7 @@ while true; do
 		-q|--quiet)   quiet=true; shift;;
 		-v|--verbose) verbose=true; shift;;
 		-h|--help)    usage; exit 0;;
-		--) shift; break;;
+		--)           shift; break;;
 		*) error "unknown option: $1"; usage; exit 1;;
 	esac
 done
diff --git a/scripts/run_scala b/scripts/run_scala
--- a/scripts/run_scala
+++ b/scripts/run_scala
@@ -6,15 +6,15 @@
 #   \/_/ /_/ \/_____/ \/_/ \/_/     \/_____/ \/_____/ \/_/\/_/ \/_____/ \/_/\/_/
 
 
-source "$HOME/.local/bin/colors_and_helpers"
-set -euo pipefail
+source "$HOME/.local/bin/colors_and_helpers" || { error "colors and helpers file not found"; exit 1; }
+set -uo pipefail
 
 # --------------------------- DEFAULT AND CONSTANTS -------------------------- #
 
 OUTPUT_DIR="out"
 MAIN_CLASS="Main"
-SCALA_CMD="scala"
-SCALAC_CMD="scalac"
+SCALA_CMD="scala3"
+SCALAC_CMD="scalac3"
 SCALAC_FLAGS=()
 
 # ------------------------------- USAGE BANNER ------------------------------- #
@@ -114,10 +114,10 @@ compile
 if [[ -n $single_file ]]; then
 	class_name=$(basename "$single_file" .scala)
 	$verbose && info "Running class $class_name"
-	$SCALA_CMD -classpath "$OUTPUT_DIR" "$class_name" "${prog_args[@]}"
+	$SCALA_CMD --classpath "$OUTPUT_DIR" --main-class "$class_name" "${prog_args[@]}"
 else
 	$verbose && info "Running main class $MAIN_CLASS with -classpath $OUTPUT_DIR"
-	$SCALA_CMD -classpath "$OUTPUT_DIR" "$MAIN_CLASS" "${prog_args[@]}"
+	$SCALA_CMD --classpath "$OUTPUT_DIR" --main-class "$MAIN_CLASS" "${prog_args[@]}"
 fi
 exit_code=$?
 
